apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-app-php
  name: user-app-php
spec:
  replicas: 4
  selector:
    matchLabels:
      app: user-app-php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-app-php
    spec:
      containers:
        - image: user-app-php:latest
          name: user-app-php
          env:
            - name: EXAMPLE_ENV_VARIABLE
              value: "example"
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.05"
            limits:
              memory: "756Mi"
              cpu: "0.1"
          ports:
            - containerPort: 80
status: {}
